controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation
show:
    path: /SasAnamaria
    controller: App\Controller\show


Qumseya-Ibrahim:
    path: /qumseya-Ibrahim
    controller: App\Controller\QumseyaIbrahimController::number

